// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package dep

import (
	"go-clean-architecture/pkg/mongodb"
	"go-clean-architecture/pkg/server"
	"go-clean-architecture/pkg/server/http"
	"go-clean-architecture/todo/delivery/http"
	"go-clean-architecture/todo/repository"
	"go-clean-architecture/todo/service"
)

// Injectors from wire.go:

func InitializeServer() (server.Server, error) {
	mongoDB, err := mongodb.NewMongoDB()
	if err != nil {
		return nil, err
	}
	mongoTodoRepository := repository.NewMongoTodoRepository(mongoDB)
	todoService := service.NewTodoService(mongoTodoRepository)
	todoHTTPHandler := handlers.NewTodoHTTPHandler(todoService)
	httpServer := pkg_http_server.NewHTTPServer(todoHTTPHandler)
	serverServer, err := server.NewServer(httpServer)
	if err != nil {
		return nil, err
	}
	return serverServer, nil
}
